sudo: required
service: 
  - docker

before_install:
  - docker build -t jtrainaldi/docker-react -f Dockerfile.dev  .

script:
  - docker run jtrainaldi/docker-react npm run test -- --coverage --maxWorkers=15
